name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1.0.4

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: build

    - name: Run native tests
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: linuxX64Test
