name: CI with Gradle

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # TODO: No assertk on mingwX64 yet: https://github.com/willowtreeapps/assertk/issues/406
          # - windows-latest
        include:
          - os: ubuntu-latest
            test_targets: linuxX64Test
          - os: macos-latest
            test_targets: macosX64Test macosArm64Test iosX64Test iosSimulatorArm64Test tvosX64Test tvosSimulatorArm64Test watchosX86Test watchosX64Test watchosSimulatorArm64Test
          # TODO: No assertk on mingwX64 yet: https://github.com/willowtreeapps/assertk/issues/406
          # - os: windows-latest
          #   test_targets: mingwX64Test

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/gradle-common

    - name: Build and test
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: build

  publish:
    name: Publish on ${{ matrix.os }}
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          # TODO: No assertk on mingwX64 yet: https://github.com/willowtreeapps/assertk/issues/406
          # - windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/gradle-common

    - name: Write secret keyring file
      shell: bash
      run: |
        set -e
        echo "$SIGNING_SECRET_KEYRING_FILE" | base64 --decode > secring.gpg
        echo "Wrote secret keyring to $PWD/secring.gpg"
      env:
        SIGNING_SECRET_KEYRING_FILE: ${{ secrets.SIGNING_SECRET_KEYRING_FILE }}

    - name: Publish release
      uses: gradle/gradle-build-action@v2.1.3
      with:
        arguments: publish -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} -Psigning.password= -Psigning.secretKeyRingFile=secring.gpg -PrealRelease=${{ startsWith(github.ref, 'refs/tags/') }}
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
